FROM node:18

ARG VITE_PRIVATE_API_URL
ENV VITE_PRIVATE_API_URL=$VITE_PRIVATE_API_URL

ARG VITE_BOT_URL
ENV VITE_BOT_URL=$VITE_BOT_URL

ARG VITE_APP_URL
ENV VITE_APP_URL=$VITE_APP_URL

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

EXPOSE 8080
CMD ["npm", "run", "preview"]